services:
  - type: web
    name: garame
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node backend/server.cjs
    envVars:
      - key: NODE_ENV
        value: production
